# Site wide configuration

title:            Werds of The Wass
locale:           en_US
url:              


# Jekyll configuration

safe: true
host: 0.0.0.0
permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

# Page Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true


# Site owner
owner:
  name: The Wass
  avatar: bio-photo.jpg
  bio: "The more you know..."
  email: lord.d35ruct0@gmail.com
  disqus-shortname: werdsofthewass
  twitter: TheWass
  facebook: #username
  google:
    plus: #username
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: TheWass
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username

include: [".htaccess"]
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "LICENSE"
  - "README.md"
